{{- if .Values.adminIdentity }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teleport-auth-stress.fullname" . }}-admin-identity
  labels:
    {{- include "teleport-auth-stress.labels" . | nindent 4 }}
type: Opaque
stringData:
  identity.pem: |
{{ .Values.adminIdentity | indent 4 }}
{{- end }}
